# Generated by Django 2.2.6 on 2019-10-27 19:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pid', models.CharField(editable=False, max_length=32, unique=True)),
                ('name', models.CharField(max_length=100, verbose_name='pro_name')),
                ('url', models.URLField(verbose_name='pro_url')),
                ('digest', models.CharField(max_length=200, verbose_name='pro_digst')),
                ('vote_count', models.IntegerField(default=0, verbose_name='pro_vote_count')),
                ('public', models.BooleanField(default=True, verbose_name='public')),
                ('remark', models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='decribtion')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'products',
                'verbose_name_plural': 'pro_manage',
                'db_table': 'product',
            },
        ),
        migrations.CreateModel(
            name='ProductVote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_time', models.IntegerField(default=0)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.Product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'vote_number',
                'verbose_name_plural': 'vote_number_manage',
                'db_table': 'product_vote',
            },
        ),
    ]
