sudo: required
services:
- docker
env:
  BUILD_TAG: wangxinyu1995/productaste:V1.${TRAVIS_BUILD_NUMBER}
  LATEST_TAG: wangxinyu1995/productaste:latest
install:
- echo "1. install "
script:
- echo "2. bulid docker image"
- docker --version
- docker build -t ${BUILD_TAG} .
- docker tag ${BUILD_TAG} ${LATEST_TAG}
after_success:
- echo "3. push docker image"
- docker login -u ${DOCKER_USER} -p ${DOCKER_PASSWORD}
- docker push ${BUILD_TAG}
- docker push ${LATEST_TAG}

before_deploy:
- openssl aes-256-cbc -K $encrypted_83e13a626f10_key -iv $encrypted_83e13a626f10_iv
  -in id_rsa.enc -out ~/.ssh/id_rsa -d
- chmod 600 ~/.ssh/id_rsa
addons:
        ssh_known_hosts: 8.206.76.179
deploy:
- ssh root@8.209.76.179 "/root/docker_pro/productaste.sh"
