sudo: required
services:
- docker
env:
  BUILD_TAG: wangxinyu1995/productaste:V1.${TRAVIS_BUILD_NUMBER}
  LATEST_TAG: wangxinyu1995/productaste:latest
install:
- echo "1. install "
script:
- echo "2. bulid docker image"
- docker --version
- docker build -t ${BUILD_TAG} .
- docker tag ${BUILD_TAG} ${LATEST_TAG}
after_success:
- echo "3. push docker image"
- docker login -u ${DOCKER_USER} -p ${DOCKER_PASSWORD}
- docker push ${BUILD_TAG}
- docker push ${LATEST_TAG}






