sudo: required
services:
- docker
- mysql
language: python
python:
  - '3.6'
env:
  global:
    - DJANGO_SETTINGS_MODULE="settings.settings"
    - PYTHONPATH=$PYTHONPATH:$(pwd)
    - PIP_USE_MIRRORS=true
    - BUILD_ON_TRAVIS=true
  BUILD_TAG: wangxinyu1995/productaste:V1.${TRAVIS_BUILD_NUMBER}
  LATEST_TAG: wangxinyu1995/productaste:latest
install:
- echo "1. install "
- pip install --upgrade pip
- pip install -r requirements.txt

- export PYTHONPATH=$PYTHONPATH:$(pwd)
before_script:

- sudo mysql -e "CREATE DATABASE test;" -u root


script:

- python manage.py test

- echo "2. bulid docker image"
- docker --version
- docker build -t ${BUILD_TAG} .
- docker tag ${BUILD_TAG} ${LATEST_TAG}
after_success:
- echo "3. push docker image"
- docker login -u ${DOCKER_USER} -p ${DOCKER_PASSWORD}
- docker push ${BUILD_TAG}
- docker push ${LATEST_TAG}






